### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Central Certificate Store_Screen Reader: NVDA is reading some invisible content(button clickable, blank clickable) after File folder when we press down arrow.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#122]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #ScreenReader; #WCAG1.3.1; #Narrator; #NVDA; #C+E-H; #Chrome; #Edge

**Environment Details:**
**URL:** https://manage.iis.net/web-sites
**Browser Details**: Chrome(68.0.3440.106)
**Screen Reader:** NVDA

**Repro Steps:**
1.Download and install "Microsoft IIS Administration" application.
2.Enable Internet information Services.
3.Open "Microsoft IIS" application using the URL: https://manage.iis.net/.
4.Tab till Web Server and press enter.
5.Tab till Central Certificate Store and press enter.
6.Tab till "Select Folder" button and press enter.
7.Start NVDA.
8.Tab till table and navigate using down arrow inside table.
6.Verify how NVDA is reading items inside table.

**Actual Result:**
NVDA is reading some invisible content(button clickable, blank clickable) after File folder when we press down arrow.

**Expected Result:**
NVDA should not read any invisible content on page.

**User Impact:** 
Screen Reader users may not know whether the content is invisible or present on page. They will find difficulty in understanding and using the application.

**Attachment:**
![bug_122_central certificate store_screen reader issue](https://user-images.githubusercontent.com/38523250/44706375-fd997180-aabe-11e8-935f-ab598b067831.png)

**Comment by jhkimnew** [comment]
This issue will be fixed if we use WAC SDK control.

**Comment by jhkimnew** [comment]
This issue happens because the controls which is behind the popup dialog is still accessible. 
This can't be fixed unless we replace the popup dialog with WAC SDK controls.

**Comment by Yashi1201** [comment]
**Github tags:** #A11ySev2;

**Comment by sspatil123** [comment]
#closed;
manage.iis.net is deprecated. The "Manage IIS" button on the www.iis.net home page will  be removed.
