### ISSUE TITLE
[Usability] A11y_Manage.IIS.Net_Web Server-Certificates: The layout appears as a Table but programmatically the section has not been identified as Table.

### ISSUE THREAD

**Issue by Shayanti123** [Microsoft/IIS.WebManager#123]
**Environment Details:**
URL:https://manage.iis.net/webserver/certificates
Browser Details: Microsoft Edge 42.17134.1.0, Google Chrome Version 68.0.3440.106

****Repro Steps**:**
1) Download and install "Microsoft IIS Administration" application.
2) Enable Internet information Services.
3) Open "Microsoft IIS" application using the URL: https://manage.iis.net/
4) Tab till Web Server and press enter
5) Tab till Certificates and press enter
6) Verify the header elements and the list of the Certificates are present inside a Table 

**Actual Result:**
The grid section present in the Certificates page is appeared as a Table but programmatically the grid cell has not been identified as Table

**Expected Result:**
The cell must be programmatically identified as Table so that user can navigate the list items present inside the grid as per their respective column header using Keyboard. 
Here in this page, on pressing "Capslock+rt.arrow" focus is directly landing on the entire cell content and narrator is reading the  contents at one go without mentioning its table header name.

**User Impact:** 
Visually Impaired Users will face difficulties in navigating and understanding the contents  if the cell is not programmatically identified as Table.

**Attachments:**
[Bug_123_The cell must be programmatically identified as Table.pptx](https://github.com/Microsoft/IIS.WebManager/files/2327211/Bug_123_The.cell.must.be.programmatically.identified.as.Table.pptx)

**Comment by jhkimnew** [comment]
This will be fixed when we use WAC SDK controls.

**Comment by Tanushagottipati** [comment]
GitHubTags: #A11yTCS; #A11yUsable; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #Edge; #C+E-H; #.NETWebsites; #Chrome
