### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Central Certificate Stote_Keyboard: Keyboard focus is not going to the "Folder path" field.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#141]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #Keyboard; #WCAG2.4.3; #C+E-H; # Chrome; #Edge

**Environment Details:**
**URL:** https://manage.iis.net/webserver/central-certificate-store
**Browser Details:** Edge(42.17134.1.0), Chrome(68.0.3440.106)
Keyboard

**Repro Steps:**
1.Download and install "Microsoft IIS Administration" application.
2.Enable Internet information Services.
3.Open "Microsoft IIS" application using the URL: https://manage.iis.net/.
4.Tab till Web Server and press enter.
5.Tab till Central Certificate Store and press enter.
6.Tab till "Select Folder" button and press enter.
7.Tab till "Folder path" field using tab.
8.Verify keyboard focus is going to the field.

**Actual Result:**
Keyboard focus is not going to the "Folder path" field.

**Expected Result:**
Keyboard focus should go to each and every control of the page.

**User Impact:** 
Keyboard only users can not perform all operations if keyboard focus is not going to all controls.

**Attachment:**

![bug_141_central certificate store_keyboard issue](https://user-images.githubusercontent.com/38523250/44766574-bae7a000-ab77-11e8-88e8-0edf8c229f73.png)

**Comment by jhkimnew** [comment]
Fixed

**Comment by Yashi1201** [comment]
**Github tags:** #A11ySev2;

**Comment by fsteffi** [comment]
#Closed;
Manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](http://www.iis.net/) home page will be removed.
