### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Mime Maps_Keyboard: Keyboard focus is going to non interactive element "Add" button.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#144]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #Keyboard; #WCAG2.4.3; #C+E-H; #Chrome; #Edge

**Environment Details:**
**URL:** https://manage.iis.net/webserver/mime-maps
**Browser Details:** Edge(42.17134.1.0), Chrome(68.0.3440.106)
Keyboard

**Repro Steps:**
1.Download and install "Microsoft IIS Administration" application.
2.Enable Internet information Services.
3.Open "Microsoft IIS" application using the URL: https://manage.iis.net/.
4.Tab till Web Server and press enter.
5.Tab till Mime Maps and press enter.
6.Navigate to all controls using tab.
7.Verify keyboard focus is going to any non interactive items.

**Actual Result:**
Keyboard focus is going to non interactive element "Add" button.

**Expected Result:**
Keyboard focus should not go to non interactive elements on page.

**User Impact:** 
Users may think that as interactive item if keyboard focus is going to that control.	

**Attachment:**
![bug_144_mime maps_focus order](https://user-images.githubusercontent.com/38523250/44767875-22541e80-ab7d-11e8-98a0-48e797add024.png)

**Comment by jhkimnew** [comment]
Fixed

**Comment by Yashi1201** [comment]
**Github tags:** #A11ySev4;
