### ISSUE TITLE
[Usability] A11y_Manage.IIS.Net_Access key Purpose: "e.g." is provided instead of example in "Access key Purpose" field.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#147]
GitHubTags: #A11yTCS; #A11yUsable; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #C+E-H; #Edge

**Environmental Details:**
**URL**:https://localhost:55539/security/tokens#
**Browser Details:** Edge(42.17134.1.0)

**Repro Steps:**
1.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
2.Download and install "Microsoft IIS Administration" application.
3.Tab till "Skip This" button and Press Enter.
4.Tab till "Get Access Token" link and Press Enter
5.Tab till "Create Access Key" button and Press Enter.

**Actual Result:**
"e.g." is provided instead of example in "Access key Purpose" field.

**Expected Result:**
Short cuts should not be given for any text.

**User Impact:** 
Screen reader users may not understand if screen reader is reading "e.g." instead of example.

**Attachment:**
![bug_147_access token _usability](https://user-images.githubusercontent.com/38523250/44769929-e7091e00-ab83-11e8-9e52-fc444630387d.png)

**Comment by InduPriya1805** [comment]
Similar issue is also observed in Web Server_Authorization Page
![bug147_web server_authorization_ex not descriptive](https://user-images.githubusercontent.com/42638450/44853092-a04e1d80-ac82-11e8-91f5-7eae14cb1ec7.png)

**Comment by jhkimnew** [comment]
Fixed
