### ISSUE TITLE
[Usability] A11y_Manage.IIS.Net_Web Server Application Pools Edit_Screen Reader:There is no Land mark in the page 

### ISSUE THREAD

**Issue by Amlan454** [Microsoft/IIS.WebManager#150]
Environment Details:
URL: https://manage.iis.net/settings/servers
Browser: Edge(42.17134.1.0)
Screen reader

Repro Steps:
1.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
2.Download and install "Microsoft IIS Administration" application.
3.Switch on Narrator
4.Tab till Microsoft IIS on top navigation bar and press enter
5.tab till web server and press enter
6.Tab till Application pool and press enter
7.tab till more button(...)and press enter
8.Click on Edit button 
9.By using the short cut key "D" check whether there is land mark present in the page or not 

Actual Result:
Land mark is not available in the page

Expected Result:
There should be land mark in the page

User Impact:
Screen Reader users will face difficulty in navigation  if land mark is not present on page

Reference Video:
Note: same issue is observed in all the pages of the application
[Bug_150_No land mark in the page.pptx](https://github.com/Microsoft/IIS.WebManager/files/2330988/Bug_150_No.land.mark.in.the.page.pptx)

**Comment by jhkimnew** [comment]
We won't need to use the land mark when we use WAC SDK.

**Comment by Tanushagottipati** [comment]
GitHubTags: #A11yTCS; #A11yUsable; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #ScreenReader; #C+E-H; #.NETWebsites; #Edge; #Narrator
