### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Access Token_Screen Reader: NVDA is reading whole sentence as two parts after access token.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#155]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #ScreenReader; #WCAG1.3.2; #NVDA; #C+E-H; #Chrome

**Environment:**
**URL:**https://localhost:55539/security/tokens#
**Browser Details:** Chrome(68.0.3440.106)
**Screen Reader**: NVDA

**Repro Steps:**
1.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
2.Download and install "Microsoft IIS Administration" application.
3.Tab till "Skip This" button and Press Enter.
4.Tab till "Get Access Token" link and Press Enter
5.Tab till "Create Access Key" button and Press Enter.
6.Tab till "Create" button and press enter.
7.Navigate to non interactive elements using down arrow.
8.Verify how NVDA is reading message provided below access token.

**Actual Result:**
NVDA is reading whole sentence as two parts after access token.

**Expected Result:**
NVDA should read whole sentence at a time instead of reading by parts.

**User Impact:** 
Screen reader users may think the whole sentence as two different sentences which is not correct. It causes inconvenience to the user.

**Attachment:**
![bug_155_access token_nvda issue](https://user-images.githubusercontent.com/38523250/44771220-0ace6300-ab88-11e8-9fb3-a1c7af03534b.png)

**Comment by jhkimnew** [comment]
Fixed

**Comment by Yashi1201** [comment]
**Github tags:** #A11ySev2;

**Comment by fsteffi** [comment]
#Closed;
Manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](http://www.iis.net/) home page will be removed.
