### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Central Certificate Stote_Screen Reader: Narrator is not reading labels for any control on page.Issue is observed through out the application.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#175]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #ScreenReader; #WCAG1.3.2; #Narrator; #NVDA; #C+E-H; #Chrome; #Edge

**Environment Details:**
**URL:** https://manage.iis.net/webserver/central-certificate-store
**Browser Details:** Edge(42.17134.1.0), Chrome(68.0.3440.106)
**Screen Reader**: NVDA, Narrator

**Repro Steps:**
1.Download and install "Microsoft IIS Administration" application.
2.Enable Internet information Services.
3.Open "Microsoft IIS" application using the URL: https://manage.iis.net/.
4.Tab till Web Server and press enter.
5.Tab till Central Certificate Store and press enter.
6. Tab to all controls using tab key and verify whether screen reader is reading labels on page.

**Actual Result:**
Narrator is not reading labels for any control on page. Issue is observed through out the application.

**NOTE: Same issue is observed in below pages.**

- Mime Maps
- Direct Browsing
- Logging
- Access Key Token
- Access Key
- Access Key Purpose

**Expected Result:**
Screen Reader should read all labels for corresponding controls.

**User Impact:** 
Screen Reader users can not use the application and they do not know the purpose of controls if screen reader is not reading labels for corresponding fields.

**Attachments:**
![bug_175_labels issue](https://user-images.githubusercontent.com/38523250/44835223-2baebb00-ac51-11e8-8efc-41b1853bb8b0.png)
![bug_175_directory browsing](https://user-images.githubusercontent.com/38523250/44835441-d0c99380-ac51-11e8-9a0a-883f9b6f1086.png)
![bug_175_logging](https://user-images.githubusercontent.com/38523250/44835442-d0c99380-ac51-11e8-9543-890cee5556ac.png)
![bug_175_mime maps](https://user-images.githubusercontent.com/38523250/44835443-d0c99380-ac51-11e8-8784-20e54c3740e9.png)

**Comment by jhkimnew** [comment]
duplicate bug to https://github.com/Microsoft/IIS.WebManager/issues/236

**Comment by jhkimnew** [comment]
Fixed

**Comment by prabhudevu** [comment]
**GitHubTags:**#A11ySev2;

**Comment by fsteffi** [comment]
#Closed;
Manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](http://www.iis.net/) home page will be removed.
