### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Central Certificate Stote_Keyboard: Keyboard focus is going to the first control of the page instead of staying in table when we press enter on any file under name header.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#179]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #Keyboard; #WCAG2.4.3; #C+E-H; #Chrome; #Edge

**Environment Details:**
**URL:** https://manage.iis.net/webserver/central-certificate-store
**Browser Details:** Edge(42.17134.1.0), Chrome(68.0.3440.106)
Keyboard

**Repro Steps:**
1.Download and install "Microsoft IIS Administration" application.
2.Enable Internet information Services.
3.Open "Microsoft IIS" application using the URL: https://manage.iis.net/.
4.Tab till Web Server and press enter.
5.Tab till Central Certificate Store and press enter.
6.Tab till "Select Folder" button and press enter.
7.Tab to table items and press enter on any file under name header and press enter.
6.Verify keyboard focus after pressing enter on file.

**Actual Result:**
Keyboard focus is going to the first control of the page instead of staying in table when we press enter on any file under name header.

**Expected Result:**
Keyboard focus should remain inside table, it should not start from first control of page when we press enter on any field.

**User Impact:** 
Keyboard only users find difficulty in using the application if keyboard focus is not as expected.

**Attachment:**
![bug_179_central certificate store_focus order](https://user-images.githubusercontent.com/38523250/44835908-1aff4480-ac53-11e8-8250-7e20c560ec11.png)

**Comment by jhkimnew** [comment]
Fixed.

**Comment by prabhudevu** [comment]
**GitHubTags:**#A11ySev2;

**Comment by fsteffi** [comment]
#Closed;
Manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](http://www.iis.net/) home page will be removed.
