### ISSUE TITLE
[Usability] A11y_Manage.IIS.Net_Web site-Edit-Web Applications: It would be better to convert the list item controls into accessible combo-box or dropdown to make it more usable for the keyboard users.

### ISSUE THREAD

**Issue by accessibility18** [Microsoft/IIS.WebManager#187]
**Environment Details**:
URL: https://manage.iis.net/
Browser: Microsoft Edge 42.17134.1.0, Google Chrome Version 68.0.3440.106

**Repro Steps:**
1. Download and install "Microsoft IIS Administration" application.
2. Enable Internet information Services.
3. Open "Microsoft IIS" application using the URL: https://manage.iis.net/
4. Tab till "Web Sites" in the left menu section and Press Enter.
5. Tab till "More" commands button of the existing website inside the grid and Press Enter.
6. Tab till "Edit" in the expanded menu and Press Enter.
7. Tab till "Web Applications" in the left menu section and Press Enter.
8. Tab till "Create Web Application" button and Press Enter.
9. Navigate to Application Pool page tab.
10. Verify that all the UI components are as per usability and design principles.

**Actual Result:**
List Item Controls provided are difficult to navigate for keyboard users. This kind of list items are rarely used and these are not that much usable and accessible to the users.

**Expected Result:**
It would be better to convert the list item controls into accessible combo-box or dropdown to make it more usable for the keyboard users. For providing list items, dropdown or combo-box should be used. This is the standard UI control that is known to all the users and navigation in these becomes more easy.

**User Impact:**
Keyboard only users will find difficulty in navigating to these kind of list items. Due to usability and accessibility issues related to these list items may create difficulty for the person with disability in accessing these controls.

**Attachment:**
![bug_187_usability issue related to list items control](https://user-images.githubusercontent.com/38521133/44844216-e8137b80-ac67-11e8-878c-19d40f7a5baa.png)

**Comment by jhkimnew** [comment]
The switch component will be replaced with WAC SDK component in the future.
