### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Modules_Screen Reader: NVDA is reading "Save" and "Cancel" buttons as only buttons.It should read as "Save" button and "Cancel" buttons.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#192]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #ScreenReader; #Narrator; #NVDA; #WCAG1.3.1; #C+E-H; #.NETWebsites; #Chrome

**Environment Details:**
**URL:** https://manage.iis.net/webserver/modules
**Browser Details:** Chrome(68.0.3440.106)
**Screen Reader:** NVDA

**Repro Steps:**
1.Download and install "Microsoft IIS Administration" application.
2.Enable Internet information Services.
3.Open "Microsoft IIS" application using the URL: https://manage.iis.net/.
4.Tab till Web Server and press enter.
5.Tab till "Modules"  and press enter.
6.Tab till "Add" button and press enter.
7.Start NVDA and tab till "Save" and "Cancel" buttons.
8.Verify how NVDA is reading "Save" and "Cancel" buttons.

**Actual Result:**
NVDA is reading "Save" and "Cancel" buttons as only buttons instead of reading "Save" button and "Cancel" button.

**Expected Result:**
NVDA should read all control names properly instead of reading only type of control.

****User Impact:**** 
Screen Reader users can not understand the purpose of the control if screen reader is not reading it's name.

**Attachment:**
[Bug_192_Modules_NVDA is reading save and cancel buttons as only buttons.pptx](https://github.com/Microsoft/IIS.WebManager/files/2335765/Bug_192_Modules_NVDA.is.reading.save.and.cancel.buttons.as.only.buttons.pptx)

**Comment by jhkimnew** [comment]
Fixed

**Comment by prabhudevu** [comment]
**GitHubTags:**#A11ySev2;

**Comment by BhanuPrakashGit** [comment]
GithubTag:#Closed;
manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.iis.net%2F&data=05%7C01%7Cv-bhaprakash%40microsoft.com%7C7a737faa4af14c4ad31a08db634ab100%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638212945750407456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q7lvppcGrDLIRxk6EaLiumHk2i6E5S784T%2BniobLEu4%3D&reserved=0) home page will  be removed.
