### ISSUE TITLE
[Usability] A11y_Manage.IIS.Net_Webserver File_Keyboard:The new folder button should be above the edit field which appear clicking on it. So user will relate the edit field and button.

### ISSUE THREAD

**Issue by Amlan454** [Microsoft/IIS.WebManager#196]
Environment Details:
URL: https://manage.iis.net/settings/servers
Browser:Chrome (68.0.3440.106), Edge

Repro Steps:
1.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
2.Download and install "Microsoft IIS Administration" application.
4.Tab till Microsoft IIS on top navigation bar and press enter
5.Tab till Web server and press enter
6.Navigate up to file and press enter
7.Tab till New root button and press enter
8.After clicking on it one Edit field is coming, So that new root folder button should be above that edit field
9.So user can easily relate the button and edit field

Actual Result:
The new folder button should be above the edit field which appear clicking on it. So user will relate the edit field and button.

Expected Result:
Edit button should above the edit field 

User Impact:
Disable users will not relate the new button with the Edit field

Reference video:
[Bug_196.pptx](https://github.com/Microsoft/IIS.WebManager/files/2335837/Bug_196.pptx)

**Comment by jhkimnew** [comment]
We moved the button group to the left side recently, which is better than before. So, I will consider that this issue is fixed.

**Comment by Tanushagottipati** [comment]
GitHubTags: #A11yTCS; #A11yUsable; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #C+E-H; #.NETWebsites; #Chrome
