### ISSUE TITLE
[Usability] A11y_Manage.IIS.Net_Web Server_Files: Narrator/NVDA is not reading the current state of the list items whether the list item is active/selected.  

### ISSUE THREAD

**Issue by Shayanti123** [Microsoft/IIS.WebManager#198]
**Environment Details:**
URL:https://manage.iis.net/webserver/certificates
Browser Details: Microsoft Edge 42.17134.1.0,Google Chrome Version 68.0.3440.106 

**Repro Steps:**
1) Download and install "Microsoft IIS Administration" application.
2) Enable Internet information Services.
3) Open "Microsoft IIS" application using the URL: https://manage.iis.net/
4) Tab till "Web Server" and press enter.
5) Start Screen Reader (Narrator/NVDA).
7) Navigate to the side navigation bar and select "Files" or any list item and press Enter
8) After opening the list item "Files", verify screen reader is reading the current state of the list item

**Actual Result:**
One list item from the side navigation bar is selected and the corresponding page is opened in the right side and if the user navigates to the side navigation bar to know which page is currently opened in that case narrator or NVDA should read currently which page is active but here narrator is reading only "4 of 20 level 1" on selecting "Files"

**Expected Result:**
Screen Reader should read the current state of the list item which is selected.

**User Impact:** 
Its become difficult for Visually Impaired Users to understand through UI which page is opened. So if Screen Reader reads which list item is in active or selected status will make the user understand easily in which page currently he/she is.

**Attachments:**
[Bug_198_Narrator or NVDA is not reading the current state of the list items whether the list item is activeselected.pptx](https://github.com/Microsoft/IIS.WebManager/files/2336161/Bug_198_Narrator.or.NVDA.is.not.reading.the.current.state.of.the.list.items.whether.the.list.item.is.activeselected.pptx)

**Comment by jhkimnew** [comment]
duplicate bug to https://github.com/Microsoft/IIS.WebManager/issues/236

**Comment by jhkimnew** [comment]
This issue will be fixed when we use WAC SDK controls.

**Comment by Tanushagottipati** [comment]
GitHubTags: #A11yTCS; #A11yUsable; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #ScreenReader; #Narrator; #C+E-H; #.NETWebsites; #Edge; #Chrome; #NVDA
