### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Web Server_IP Restriction_Screen Reader: At Max Concurrent Request, Max Requests and  Per Time Period labels narrator is reading instructions wrongly

### ISSUE THREAD

**Issue by InduPriya1805** [Microsoft/IIS.WebManager#199]
GitHubTags: #A11y_Manage.IIS.Net; #A11yMAS; #A11yTCS; #C+E-H; #DesktopWeb; #Win10; #.NETWebsites; #Edge; #ScreenReader; #Narrator

**Environment Details:**
URL: https://manage.iis.net/webserver/ip-restrictions
Browser Details: Microsoft Edge 42.17134.1.0
Screen Reader: Narrator

**Repro Steps:**
1. Download and install "Microsoft IIS Administration" application.
2. Enable Internet information Services.
3. Open "Microsoft IIS" application using the URL: https://manage.iis.net/
4. Tab till Web Server and press enter
5. Tab till IP Restrictions and press enter
6. Tab till Max Concurrent Request, Max Requests and  Per Time Period labels and verify narrator is reading instructions correctly or not

**Actual Result:**
At Max Concurrent Request, Max Requests and  Per Time Period labels  narrator is reading instructions wrongly

**Expected Result:**
At Max Concurrent Request, Max Requests and  Per Time Period labels  narrator should read the correct instructions

**User Impact:**
Screen Reader users perceive wrong information if narrator reads the wrong instructions

**Note:**
This issue is observed in all pages which has spin buttons

**Attachments:**
 
[Bug199_IP Restrictions_Narrator reading wrong instructions.pptx](https://github.com/Microsoft/IIS.WebManager/files/2336162/Bug199_IP.Restrictions_Narrator.reading.wrong.instructions.pptx)

**Comment by jhkimnew** [comment]
Seems to be fixed while fixing other issues.

**Comment by prabhudevu** [comment]
**GitHubTags:**#A11ySev2;

**Comment by BhanuPrakashGit** [comment]
GithubTag:#Closed;
manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.iis.net%2F&data=05%7C01%7Cv-bhaprakash%40microsoft.com%7C7a737faa4af14c4ad31a08db634ab100%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638212945750407456%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q7lvppcGrDLIRxk6EaLiumHk2i6E5S784T%2BniobLEu4%3D&reserved=0) home page will be removed.
