### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Web Server_IP Restriction_Screen Reader: At Max Concurrent Request, Max Requests and Per Time Period labels narrator is reading instructions twice

### ISSUE THREAD

**Issue by InduPriya1805** [Microsoft/IIS.WebManager#200]
GitHubTags: #A11y_Manage.IIS.Net; #A11yMAS; #A11yTCS; #C+E-H; #DesktopWeb; #Win10; #.NETWebsites; #Edge; #ScreenReader; #Narrator; 

**Environment Details:**
URL: https://manage.iis.net/webserver/ip-restrictions
Browser Details: Microsoft Edge 42.17134.1.0
Screen Reader: Narrator

**Repro Steps:**
1. Download and install "Microsoft IIS Administration" application.
2. Enable Internet information Services.
3. Open "Microsoft IIS" application using the URL: https://manage.iis.net/
4. Tab till Web Server and press enter
5. Tab till IP Restrictions and press enter
6. Tab till Max Concurrent Request, Max Requests and  Per Time Period labels and verify narrator is reading instructions twice or not

**Actual Result:**
At Max Concurrent Request, Max Requests and  Per Time Period labels  narrator is reading instructions twice

**Expected Result:**
At Max Concurrent Request, Max Requests and  Per Time Period labels  narrator should not read the instructions twice

**User Impact:**
Screen Reader users may find confused while working with the application if narrator read the instructions twice

**Attachments:**
 
[Bug200_IP Restrictions_Narrator reading the instructions twice.pptx](https://github.com/Microsoft/IIS.WebManager/files/2336204/Bug200_IP.Restrictions_Narrator.reading.the.instructions.twice.pptx)

**Comment by jhkimnew** [comment]
Fixed

**Comment by prabhudevu** [comment]
**GitHubTags:**#A11ySev3;
