### ISSUE TITLE
[Usability] A11y_Manage.IIS.Net_Web Server_Keyboard: No shortcut is provided for "Restart" button for users to make their actions quickly. 

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#203]
GitHubTags: #A11yTCS; #A11yUsable; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #Keyboard; #C+E-H; #.NETWebsites; #Edge

**Environment Details:**
**URL**: https://manage.iis.net/webserver/general
Browser Details: Edge(42.17134.1.0)

**Repro Steps:**
1.Download and install "Microsoft IIS Administration" application.
2.Enable Internet information Services.
3.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
4.Tab till "Web Server" in the left menu section and Press Enter.
5.Verify any shortcut button is provided for "restart".

**Actual Result:**
No shortcut is provided for "Restart" button for user to make their actions quickly.

**Expected Result:**
Shortcut should be provided for "restart" to make users work easy.

**User Impact:** 
Users can easily perform operations if shortcuts are provided, otherwise they need to navigate to some other control to perform actions. Shortcuts save users time.

**Attachment:**
![bug_203_web server_usability](https://user-images.githubusercontent.com/38523250/44895097-6cb9d480-ad10-11e8-8a79-ead093fe1454.png)

**Comment by jhkimnew** [comment]
Supporting hot key should be considered as VNext feature request. 
I am assigning this bug to @shhsu for triaging if this feature can be done in the future release.
