### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by dhirschfeld** [Microsoft/IIS.WebManager#218]
How come all the useful build information in the README was removed in https://github.com/Microsoft/IIS.WebManager/commit/fdcfd2d33a854558c5c5349148f233cb97f67917#diff-04c6e90faac2675aa89e2176d2eec7d8?

Are those instructions no longer valid? If so, how should one go about building this app?

**Comment by dhirschfeld** [comment]
I failed to build master so maybe that's why the instructions have been removed?

I was however able to build PR #51 and run that...

**Comment by shhsu** [comment]
sorry, the branch was in a unstable stage. Wit the checkin https://github.com/Microsoft/IIS.WebManager/commit/954bb5b3224e15697b8034e822032cb6fb203948, you will be able to build the project with `.\build.ps1`
