### ISSUE TITLE
Navigating with Tab key does not work when IIS.WebManager is launched via WAC(Windows Admin Center)

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#227]
1. Install IIS.WebManager extenstion to Windows Admin Center
2. Start WAC and open IIS feature
3. Try to navigate IIS.WebManager UI controls with tab keys

EXPECTED:

Tab key should navigate all IIS.Wemanager UI controls.

ACTUAL:

Tab key works differently comparing when IIS.WebManager is started alone without using WAC.

**Comment by shirhatti** [comment]
Dupe of #231
