### ISSUE TITLE
getting slower after visiting Mime Maps feature

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#254]
Steps to Repro:
1.	Start IIS.WebManager
2.	Select Web Sites feature 
3.	Select Mime Maps feature
4.	Select Web Sites feature again

EXPECTED:

There should be no performance difference showing Web Sites feature

ACTUAL:

Showing Web Sites feature becomes slower.
According to the below Performance data, it seems that there are repeated adding removing list items, which took 2.62 seconds.

![image](https://user-images.githubusercontent.com/20650163/50792771-fbb89980-127a-11e9-865f-8f3b9e353f17.png)

**Comment by shhsu** [comment]
Currently it is not repoing on my side. Please check out the branch https://github.com/Microsoft/IIS.WebManager/pull/257 and see if we still have the same issue

**Comment by jhkimnew** [comment]
@shhsu: This is still reproducible. 
However, I confirmed this is not a regression because https://manage.iis.net shows the same problem.
