### ISSUE TITLE
Change acquisition screen when the API is not installed 

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.WebManager#268]
Current
![image](https://user-images.githubusercontent.com/4734691/51138859-24024400-17f7-11e9-9edb-af969cdd42c6.png)

Desired
![image](https://user-images.githubusercontent.com/4734691/51138906-409e7c00-17f7-11e9-8481-da481f2f5e0d.png)

**Comment by shirhatti** [comment]
@tanyastockland We'll need more design input here. As the original screenshot actually has two input boxes: one for installing the IIS.Administration API, and the second for installing the .NET Core runtime.

@shhsu Can you please paste in the current screenshot from dev

**Comment by shirhatti** [comment]
This is at risk for the first preview

**Comment by tanyastockland** [comment]
Hey Sourabh,

Just to make sure I’m clear, are you saying I need to add two input boxes total instead of one?

Thanks,
Tanya

**Comment by shirhatti** [comment]
@tanyastockland Yes. There are two input boxes instead of one.

**Comment by shhsu** [comment]
This is the new screenshot

![image](https://user-images.githubusercontent.com/6619915/52306897-059eec80-294e-11e9-9ea6-073eae69a7f3.png)

**Comment by tanyastockland** [comment]
Got it, thanks, I’ll get something to you by EOD.

**Comment by tanyastockland** [comment]
![screen shot 2019-02-06 at 11 16 19 am](https://user-images.githubusercontent.com/46721345/52367490-12304d00-2a01-11e9-8b35-687e154f79a7.png)

**Comment by shhsu** [comment]
@tanyastockland 
I was thinking of making the radio button nested. Note that .NET core runtime from custom location only make sense when IIS Admin API is installed from custom location

**Comment by shhsu** [comment]
It would make sense to hide the .NET core Runtime part if we are install api from microsoft. My question would be whether to indent the .NET core Runtime or not

**Comment by tanyastockland** [comment]
Could we do something like this
![screen shot 2019-02-06 at 12 24 50 pm](https://user-images.githubusercontent.com/46721345/52371417-5411c100-2a0a-11e9-941c-f98e3d0c9cea.png)

**Comment by tanyastockland** [comment]
![screen shot 2019-02-06 at 12 25 00 pm](https://user-images.githubusercontent.com/46721345/52371430-5ecc5600-2a0a-11e9-9dbd-598c249bf0ee.png)

**Comment by shhsu** [comment]
PR created https://github.com/Microsoft/IIS.WebManager/pull/307/files

**Comment by ghost** [comment]
@shhsu From a screenshot Sourabh shared, it looks like the "install" button still says "Install on <servername>". Button should just say "Install"
