### ISSUE TITLE
Heading in the nav bar should be context aware

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.WebManager#270]

**Comment by shirhatti** [comment]
![image](https://user-images.githubusercontent.com/4734691/51139044-a7239a00-17f7-11e9-8812-a2580ab1ad65.png)

Notice that the title says Web Server tools because we are in the web server context

**Comment by shirhatti** [comment]
![image](https://user-images.githubusercontent.com/4734691/51139234-24e7a580-17f8-11e9-8cf8-40d72120e3d8.png)

**Comment by tanyastockland** [comment]
Here's an updated image for reference:
![3 iis web sites - settings](https://user-images.githubusercontent.com/46721345/51197926-b104d600-18a7-11e9-8bf1-d069b2b76b2a.png)

**Comment by shhsu** [comment]
With breadcrumb implements, do we still need the headings?
![wac_webapp](https://user-images.githubusercontent.com/6619915/56754826-d032bf80-6742-11e9-9100-3a95dc708f02.PNG)
![wac_website](https://user-images.githubusercontent.com/6619915/56754835-d2951980-6742-11e9-8bb4-2147663ab7a3.PNG)

**Comment by tanyastockland** [comment]
Hi Peter,

I’m no longer on WAC. I’ve cc’d both Archana and Brian who can respond.

Thanks!
Tanya

**Comment by tanyastockland** [comment]
Moving Tanya to bcc

Hey Peter, I see your point. But I'd still keep the headings for couple of reasons

  *   The breadcrumb may get too long and not noticeable for some cases.
  *   Today they are just above the content and have a noticeable font. But in future we can't predict how this may change, it may become compact, change position etc.
  *   Title provides a consistent place for users to look.

Thanks,
Archana

**Comment by shhsu** [comment]
fixed https://github.com/microsoft/IIS.WebManager/pull/357
