### ISSUE TITLE
Move actions into a context menu above the list of all items

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.WebManager#271]
![image](https://user-images.githubusercontent.com/4734691/51139153-efdb5300-17f7-11e9-8cd3-edc1cebec7dd.png)

**Comment by tanyastockland** [comment]
Here's an updated image for reference:
![2 iis web sites](https://user-images.githubusercontent.com/46721345/51198027-f75a3500-18a7-11e9-8954-e8da09512ee6.png)

**Comment by shirhatti** [comment]
@shhsu 	Can we have a cost estimate?

**Comment by shhsu** [comment]
#357 fixes the issue for most views: website list, app-pool list, certificate list, web app list
File lists and vdir list requires further effort and designing, opening new items
#370 #371
