### ISSUE TITLE
Add labels to feature-level toggles

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.WebManager#272]
![image](https://user-images.githubusercontent.com/4734691/51139346-742dd600-17f8-11e9-9490-60aa9814445f.png)

**Comment by tanyastockland** [comment]
Here's an design for reference:
![iis central certificate store](https://user-images.githubusercontent.com/46721345/51199404-7a30bf00-18ab-11e9-9bec-c08a0e07dbea.png)

**Comment by shhsu** [comment]
This feature requires a major refactoring. We should actually lower priority of this feature

**Comment by shirhatti** [comment]
If you remove it from the milestone, please assign a cost

**Comment by shhsu** [comment]
Planning to move the switch to be next to feature headings

**Comment by shhsu** [comment]
fixed https://github.com/microsoft/IIS.WebManager/pull/357
