### ISSUE TITLE
Set up CI to publish WAC build to MyGet

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.WebManager#274]
First build was manually uploaded to https://www.myget.org/feed/iis-wac/package/nuget/microsoft.iis-wac-extension

You can add the feed `https://www.myget.org/F/iis-wac/api/v2` to WAC to install the IIS extension

**Comment by shhsu** [comment]
I created a VSTS workflow that builds dev branch and push to above nuget feed.
