### ISSUE TITLE
Getting SSl error while debuging application in vs2017, typescript 2.3

### ISSUE THREAD

**Issue by babula38** [Microsoft/IIS.WebManager#28]
Hi,
I am trying to run the application in VS2017. but I am getting **ERR_SSL_PROTOCOL_ERROR** in browser.

Steps I took to debug:-
 

- Download the source code and extract to a location.

- Run vs2017 in Admin mode and open the application.

- try to run the application using F5.

Expected behaviour:- the application should run without any issue.

Actual behaviour:- Getting SSL error.

Steps took to solve the issue:-

1. Try to change the "Project Url" port to 44327 (Did not work)

2. Edit the .csproj file **DevelopmentServerPort** to same port above (Did not work).

run the below command to check SSl is enable to this port or not.

**netsh http show sslcert ipport="0.0.0.0:44327"** 

Below is the screen shot of that, I guess SSL is active in this port

![mana](https://user-images.githubusercontent.com/4153708/32132319-88ba8f1c-bbdf-11e7-86b6-adaf6d8d075b.PNG)

**Comment by jimmyca15** [comment]
@babula38 

Debugging the application in IIS Express is not something I tend to do because it has an SSL upgrade URL rewrite rule. 

Are you able to build the application?

If so then you can do what I do, which is host the web site in IIS. Just point a web site to the root of the IIS.WebManager repository. Make sure that the web site has an HTTPS binding.

**Comment by jimmyca15** [comment]
However, if you changed the port to 44327 as long as HTTPS is enabled it should work. Did you make sure to enable HTTPS (SSL) on the development port?

**Comment by jimmyca15** [comment]
@babula38 

I just created a new branch titled vs2017. Development on the IIS.WebManager has been done in VS 2015 but I think it is time we migrate to vs 2017. Can you try the branch and see if it solves your issues? It uses Type Script tools 2.5

**Comment by ghost** [comment]
@jimmyca15 Angular 5.0 upgrade time too?

**Comment by babula38** [comment]
@jimmyca15 vs2017 branch is working fine now, I guess it was not e with the branch, it was issue with my system and SSL certificate binding.

@jimmyca15 Thanks lot.
