### ISSUE TITLE
DOC: There should be a clear guideline of updating appsettings.xml.

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#285]
If users are not supposed to change the permission, I think we should update the existing documentation https://docs.microsoft.com/en-us/iis-administration/configuration/appsettings.json#default-settings. That does not explain clearly about that.

https://github.com/Microsoft/IIS.WebManager/issues/263

**Comment by jhkimnew** [comment]
Currently there is no API for CORS settings in IISAdministraiton API. That means users still need to update the appsettings.xml file manually in order to update CORS settings. 

Currently, the work-around way is to give the full permission for the admin user who is responsible to manage the appsettings.xml.

Here is an example of Powershell script.

```
### Replace any existing access control for the currently logon user with the full permission 
$user = $(whoami)
$path = "$env:ProgramFiles\IIS Administration\2.2.0"
 
$dirAcl = get-acl $path
foreach ($access in $dirAcl.Access | Where-Object { $_.IdentityReference.Value -eq $user }) {
    Write-Host "remove the existing access control for the currently logon user"
    $dirAcl.RemoveAccessRule($access)
    Set-Acl -Path $path -AclObject $dirAcl
}
 
Write-Host "give full permission for the currently logon user"
$dirAcl = get-acl $path
$rights = [System.Security.AccessControl.FileSystemRights]::FullControl
$inheritFlags = [System.Security.AccessControl.InheritanceFlags]::ContainerInherit -bOr [System.Security.AccessControl.InheritanceFlags]::ObjectInherit
$propFlags = [System.Security.AccessControl.PropagationFlags]::None
$ar = New-Object System.Security.AccessControl.FileSystemAccessRule($user, $rights, $inheritFlags, $propFlags, "allow")
$dirAcl.SetAccessRule($ar)
Set-Acl -Path $path -AclObject $dirAcl
```

**Comment by shirhatti** [comment]
@jhkimnew Please move issue to https://github.com/MicrosoftDocs/IIS.Administration-docs
