### ISSUE TITLE
Handle ERROR_SUCCESS_REBOOT_REQUIRED when enabling/disabling features

### ISSUE THREAD

**Issue by shhsu** [Microsoft/IIS.WebManager#334]
### Describe the bug
related to https://github.com/Microsoft/IIS.Administration/issues/236. When  ERROR_SUCCESS_REBOOT_REQUIRED is returned by IIS.Administration, the front end need to know how to handle it.

### To Reproduce
Enable/Disable Central Certificate

### Expected behavior
To be researched

### Additional context
When trying to enable central certificates, IIS Administration API now returns 500 status code and the site would show a big error banner

**Comment by shhsu** [comment]
BTW, `ERROR_SUCCESS_REBOOT_REQUIRED` == `3010`

**Comment by shhsu** [comment]
From extensive test, we found the following

> We tried some features such as, Basic Authentication, IP and Domain Restrictions which get passed. 
> But when trying install Static content Compression and Dynamic Content Compression (corresponding to Response Compression section) from IIS.WebManager, we get error 32.

**Comment by qmutz** [comment]
RPM - REAL PROCESS MATRIX - or BINARY abstraction layer ... LINUX would not incur this so compiling into the I I S would of course STD_OUT as a SUB PROCESS and is not necessary to compile RPM ... I I S itself can lead you into that DIRECTORY of abstraction layer as the two LAYERS of EXECUTABLE OR CAB files are very similar to RPM which hold the DRIVERS inherit of motor or STEPPER MOTORS . . . SM is serial marks and DRIVERS are DYNAMIC LINK LIBRARIES that reference to and from ABSTRACTS of BINARY layers that reside within SERVER VARIANTS MOTORS . . . S V M . SCALAR VOLTAGE MATRIX the output is S V N like REM or NOTES that refer to NUMBERS or KEY_INPUT as inherit of the PROCESSOR.
