### ISSUE TITLE
IIS.WebManager will fail if the target server is x86 platform because IIS.Administration API does not support x86 platform.

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#344]
IIS.WebManager will fail if the target server is x86 platform because IIS.Administration API does not support x86 platform.

We should show a proper error message in that case that IIS.Administration API does support x86.

**Comment by shhsu** [comment]
IIS administration API will not support x86 machine for now. We can add logic to gracefully handle this error.
