### ISSUE TITLE
Under WAC, The link of web applications in Files module does not work

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#348]
1. Create a new web application for Default Web Site
2. Go to the Files feature page of the Default Web Site
3. Click the link of the web application

EXPECTED:

The link work.

ACTUAL:

The link does not work. I showed the symptom to Pan in person.

**Comment by shhsu** [comment]
@jhkimnew  , can you take a look at this issue?

**Comment by shhsu** [comment]
I can help with the context of the issue, but might not have time to implement a solution before preview

**Comment by shhsu** [comment]
I will be taking a look. File navigation under web site view is completely messed up

**Comment by shhsu** [comment]
https://github.com/microsoft/IIS.WebManager/pull/377

**Comment by shhsu** [comment]
Another issue found while trying to fix this https://github.com/microsoft/IIS.WebManager/issues/378
