### ISSUE TITLE
UI: The vertical line after apppool modules is too short.

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#351]
Here is the screenshot of the issue. 

![image](https://user-images.githubusercontent.com/20650163/57109115-81100000-6ce9-11e9-9cfd-265d34c4dc17.png)

**Comment by shhsu** [comment]
https://github.com/Microsoft/IIS.WebManager/pull/357 will address it

**Comment by shhsu** [comment]
fixed
