### ISSUE TITLE
No error handling against invalid web.config

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#374]
STEPS TO REPRO:

1. create a web.config of any existing web application
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <bogus>
      <add name="bogus" path="*" verb="*" modules="bogus" resourceType="Unspecified" />
    </bogus>
  </system.webServer>
</configuration>
```

2. Open https://manage.iis.net and go to the web application

EXPECTED:

Error message is shown that the web.config is invalid

ACTUAL:

No error message and the fewer features is shown

![image](https://user-images.githubusercontent.com/20650163/57953663-8e121f00-78a5-11e9-956c-616b6602c253.png)

**Comment by shhsu** [comment]
If the physical directory of the web site/application doesn't exist, the error handling is even worse and the feature pages of the website/application are set into a totally unusable state.
