### ISSUE TITLE
Users should be able to update the site configuration even it is using not-existing apppool

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#393]
In the site level, the status does not work if the site is using an apppool which is removed.
Attached the screenshot which shows the symptom.

![image](https://user-images.githubusercontent.com/20650163/59805686-ce9af900-92a6-11e9-8e12-8a59eac78f20.png)

**Comment by shhsu** [comment]
https://github.com/microsoft/IIS.WebManager/pull/401 will fix the problem with broken heading.

However, the start/stop/restart button are still hiding. The would only come back if the user refresh the page. This could be a IIS Administration API issue. It seems like after model is update the site. The status remains "unknown"
