### ISSUE TITLE
ASP.Net_SessionId always remains unsecured for the first session

### ISSUE THREAD

**Issue by Gautam2010** [Microsoft/IIS.WebManager#398]
Just checked MVC project added code in session_start to check 
If connection is secure than 
Response.Cookies["ASP.NET_SessionId"].Secure=true
It works fine. 
But once Resseting IIS first session always get created on nonsecured cookies

**Comment by jhkimnew** [comment]
@Gautam2010 I think you used a wrong repository. This repository is only for IIS.Webadministration UI tool, not for general IIS or ASP.NET issues.

Please close this issue after opening the issue on the right place.

**Comment by shhsu** [comment]
closing
