### ISSUE TITLE
Settings button on Create AppPool page does not work

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#406]
Settings button on Create AppPool page does not work.

![image](https://user-images.githubusercontent.com/20650163/60136413-f384e580-9758-11e9-92b3-20e02a56bbcf.png)

**Comment by shhsu** [comment]
https://github.com/microsoft/IIS.WebManager/pull/440

**Comment by shhsu** [comment]
Removed the toggle as we are not using it anywhere else and this breaks the pattern
