### ISSUE TITLE
There are duplicated value shown in the drop down button of the Web Site item

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#410]
I ran into an issue of duplicated value for web site binding even though there was a single web site binding. However this issue is not always reproducible. I need to figure out the repro step.

![image](https://user-images.githubusercontent.com/20650163/60206292-0acedc00-9808-11e9-9725-31480fdb5f8c.png)

**Comment by shirhatti** [comment]
Will re-visit if we can repro

**Comment by jhkimnew** [comment]
Not reproducible and the issue can be fixed with refreshing the page.
