### ISSUE TITLE
The compare toggle button does not work in the File edit page

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#426]
I found two regression issues comparing to manage.iis.net.

1. The compare toggle button does not work in the File edit page. When I click the compare button, it shows the compare UI but I can't finish the compare mode.
2. In the page, there are small sized window shown, which does not happen in manage.iis.net.

![image](https://user-images.githubusercontent.com/20650163/60463594-494a0980-9c01-11e9-8bc6-ae6eecd2dbca.png)

**Comment by shirhatti** [comment]
For the preview, let’s just remove the compare button.

Make sure to create another issue to track the remaining work
