### ISSUE TITLE
Improve UX for creating new virtual filesystem root

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.WebManager#432]
![image](https://user-images.githubusercontent.com/4734691/61418497-91c71f80-a8af-11e9-832b-ff108abfb778.png)

The user study indicated that users aren’t sure how to create a new virtual file system root.

- [x] The folder names aren't clickable. #435
  - Most participants expected to navigate into a folder by clicking the name.
  - The focus state on the file name was confusing.
- [x] Don't include two focus states on click, the blue highlight is already a focus state. Focus on the whole grid item, or only show sub-focus state when invoked by the tab.
- [x] The new root icon isn't immediately discoverable.
  - Add a label.
  - Some participants didn't realize they needed to create a new root after clicking on the icon. 
  - This was because the wording was unclear. 
  - Consider different wording for the hover text: “Add existing folder”
- [x] Navigating within a folder is slow, taking a few seconds to load. There's no loading animation.
  - Add a loading animation.
  - There's no empty state saying there are not contents within a folder.
- [x] Folders can only be selected at the parent level. Once inside a folder, there's no way to add that folder, which isn't a common pattern.
- [x] Allow users to add the current directory folder when no sub-directories are selected (OneDrive does this).
  - It's unclear that this is a virtual folder system mapped to the system drive, and to add new folders you have to map them.
- [x] Add a column for mapping next to name.
- [x] Add a a heading and short description at the top of the modal describing this is a virtual file system.
  - Add modal title: “Select a directory for the application”
  - Add modal description: “…”
  - The term physical path is misleading.
  - Consider different strings.
  - It was misleading to enable the navigate back icon.
- [x] Disable the icon at the root level.

**Comment by shhsu** [comment]
* Don't include two focus states on click, the blue highlight is already a focus state. Focus on the whole grid item, or only show sub-focus state when invoked by the tab.

I would argue after fixing https://github.com/microsoft/IIS.WebManager/pull/441, this point become less of an issue because user would be navigated into the link right after clicking on it. The fact that there's a focus outline actually enable user to know that the cursor is on this link when navigating via keyboard

**Comment by shhsu** [comment]
![image](https://user-images.githubusercontent.com/6619915/61668448-8ac65580-ac91-11e9-8d0c-ab2b461f422a.png)

https://github.com/microsoft/IIS.WebManager/pull/445
