### ISSUE TITLE
Enable tabbed navigation for input fields

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/IIS.WebManager#439]

**Comment by shhsu** [comment]
Talked to @jhkimnew 

* We don't have any multi line text area, the user should be using arrow key to navigate between text boxes
* In WAC we do not have a way of letting use use both arrow and tab to navigate to next input element. We can either
    - choose to let them use arrow, which is current behavior. (As we did not mark the text input at its own sme-focus-zone)
    - choose to them them use tab key and arrow won't work (mark the text input as its own sme-focus-zone)

As a compromise we can still implement something at the root level and capture all tab key from text inputs and switch focus programmatically. but
1. This is not WAC default behavior, might be confusing
2. The impact of this chance is high and relatively risky.

We should not do it for public preview
