### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by liuyanchen1994** [Microsoft/IIS.WebManager#44]
How do you deploy to IIS and direct HTTP access?
I download the vs2017 branch to run directly, but I'm sending the generated files to IIS to prompt HTTP Error 500.19 - Internal Server Error.
@dcl-lily  我用你编译好的部署到IIS上提示错误，能给我说下怎么部署的么

**Comment by dcl-lily** [comment]
hi
当初没有记忆做其他设置了，解压放到IIS目录下就可以使用的
https://manage.qnjslm.com/  

如果源码编译，我当初遇到很多问题的。

**Comment by jimmyca15** [comment]
Can you elaborate further on what the issue is? Where are you trying to deploy? Are you just trying to debug?

**Comment by liuyanchen1994** [comment]
@jimmyca15  I have deployed to Windows IIS, and I can't find the relevant resources. Is there any reference document to be deployed to IIS?

**Comment by liuyanchen1994** [comment]
@dcl-lily 是要放在IIS的根目录么？我设置其他端口提示webconfig这个文件错误，我源码编译通过了，部署到IIS上访问提示  HTTP 错误 404.0 - Not Found
您要找的资源已被删除、已更名或暂时不可用。

**Comment by liuyanchen1994** [comment]
The reason for this is that the local IIS does not have a URL rewriting plug-in installed by default, which can be redeployed after installation alone.
