### ISSUE TITLE
Locally compiled version is looking for resources not included in the folders

### ISSUE THREAD

**Issue by Ngobskie** [Microsoft/IIS.WebManager#46]
I was able to compile the cloned files and added it to my local IIS server. When I tried to access it, it's looking for resources not included in the compiled folders. (i.e. main.v2.2.1.js). The compiled version doesn't have version number in it while the application is looking for the resource with the version number in the filename. Hope you can help me with this.

thank you very much

**Comment by jimmyca15** [comment]
The v2.2.1 in the main.js that you mention is used to version the UI. This part of the file name is removed by the _Remove Version_ rule in the web.config. In order for this rule to execute URL Rewrite must be installed on the server that is hosting the UI.

Do you have URL Rewrite installed?

**Comment by Ngobskie** [comment]
I see, I'll have this configured in my web server and I'll let you know the result. Thank you Jimmy..

**Comment by Ngobskie** [comment]
Hi Jimmy,
Tried enabling the url rewrite and it's now working...thank you :)
