### ISSUE TITLE
Error message shows "null" value and a typo.

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#460]
@shhsu  When I tried to create a new physical directory while I have only read permission to the root path, I got this error. The error message contains "null" and a typo (if => If).

![image](https://user-images.githubusercontent.com/20650163/61898483-4673c900-aece-11e9-89bc-a675f86d91c6.png)

**Comment by shhsu** [comment]
https://github.com/microsoft/IIS.WebManager/pull/462
Fixes here
