### ISSUE TITLE
UI Truncation issue on the Action-Selector Menu

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#463]
![image](https://user-images.githubusercontent.com/20650163/61904893-abceb680-aedc-11e9-9512-eccedd13869b.png)

**Comment by jhkimnew** [comment]
Assigning this bug to @shhsu because he has already found the root cause.

**Comment by shhsu** [comment]
For reason unknown to me , the selector div was auto sized but the sizing does not take into account of the margin of its content. If we set the margin to 0 for all buttons passed into selectors marked as isQuickMenu, the problem would be solved.
