### ISSUE TITLE
Upload/Download, New/Edit File does not work because the request serialization is broken for the file content.

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#464]
@shhsu Currently Upload/Download and New/Edit File does not work if the file is saved using UTF-8 with BOM. If we can't fix this issue, I think we should disable the Upload/Download and New File buttons and then remove the link for the physical file in order to disable the Edit File feature.

**Comment by shhsu** [comment]
For context, because WAC mode uses powershell to proxy the requests and encode http requests as json, it messes up any file edit/download/upload for any files that are not utf-8

**Comment by shhsu** [comment]
The proper solution is to bypass IIS Admimistration API and use WAC's FileTransferService
