### ISSUE TITLE
Download API under WAC does not work 

### ISSUE THREAD

**Issue by jhkimnew** [Microsoft/IIS.WebManager#479]
In order to make the Download API, it seems that we need do two steps as the below example, which I got from tracing log while downloading a file. 

1. First request: POST: https://localhost:55539/api/files/downloads

Request Body: {name: "test_unicode_le.htm", id: "nyqEe4R96Eya3yRtbGGf2s2b7EYUporh7VoerWuiZDiCYaOfjeUiRYLoEjNNRj6C",…}

2. Second request: GET: https://localhost:55539/downloads/aYGSC46lP6fTM2LtOTEXqXA2_6jPeGwJq-

Under WAC, we do the first request correctly but the second request does not happen.

**Comment by jhkimnew** [comment]
@shhsu  I'd like to remind you that the Download API is used by both "Files" and "Request Tracing".

**Comment by shhsu** [comment]
https://github.com/microsoft/IIS.WebManager/pull/487
