### ISSUE TITLE
Lacks compiled release - installer...

### ISSUE THREAD

**Issue by dawesi** [Microsoft/IIS.WebManager#49]
Without a compiled binary installer this is useless to a large group of people who would use this.

Could you please compile and release a binary for people to install. 

I would use this but there's no way in hell I'm installing VS just to use your project, and why should I? You could in minutes compile and upload a release. Can you please do that.

This is a brilliant idea, that falls before the finishing line. Remember MOST people using iis don't code in .net nor have VS. 80%+ of your audience won't have VS on their machine but want a rest api for IIS. #sigh

**Comment by shhsu** [comment]
With my PR https://github.com/Microsoft/IIS.WebManager/pull/51/files. We would be able to ship a standalone app. Stay tuned
