### ISSUE TITLE
Error when accessing the websites tab and application pools tab

### ISSUE THREAD

**Issue by afoster757** [Microsoft/IIS.WebManager#497]
After getting all of the prereqs installed and running the module the following error is generated when trying to list the websites or application pools:

{"message":"ajax error 400","name":"AjaxError","xhr":{"__zone_symbol__timeoutfalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:timeout","zone":"angular","runCount":0}],"__zone_symbol__errorfalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:error","zone":"angular","runCount":0}],"__zone_symbol__readystatechangefalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:readystatechange","zone":"angular","runCount":8}],"__zone_symbol__loadfalse":[{"type":"eventTask","state":"running","source":"XMLHttpRequest.addEventListener:load","zone":"angular","runCount":2}],"__zone_symbol__xhrSync":false,"__zone_symbol__xhrURL":"https://admingw.eneighborhoods.com/api/nodes/nfhcweb01.eneighborhoods.com/features/powershellApi/pssessions/b7b86cfa-99c3-4c27-905a-5b6ec96cf647?$expand=output&api-version=2019-02-01","__zone_symbol__xhrTask":{"type":"macroTask","state":"notScheduled","source":"XMLHttpRequest.send","zone":"angular","runCount":0}},"request":{"async":true,"crossDomain":true,"withCredentials":true,"headers":{"x-ms-sme-module-name":"msft.iis.iis-management","x-ms-sme-module-version":"1573574477953","Content-Type":"application/json; charset=utf-8","Accept":"application/json, text/plain, */*","x-xsrf-token":"fc65a40a-1d70-4ec4-bddb-f914be773f46"},"method":"GET","responseType":"json","timeout":0,"retryHandlers":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],"url":"https://admingw.eneighborhoods.com/api/nodes/nfhcweb01.eneighborhoods.com/features/powershellApi/pssessions/b7b86cfa-99c3-4c27-905a-5b6ec96cf647?$expand=output&api-version=2019-02-01","body":"","maxRetryCount":3},"status":400,"responseType":"json","response":{"sessionId":"b7b86cfa-99c3-4c27-905a-5b6ec96cf647","completed":"True","results":[],"errors":[{"errorType":"RemoteException","message":"Exception calling \"GetResult\" with \"0\" argument(s): \"A task was canceled.\"","detailRecord":{"hResult":-2146233087,"remoteExceptionMessage":"System.Management.Automation.MethodInvocationException: Exception calling \"GetResult\" with \"0\" argument(s): \"A task was canceled.\" ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at CallSite.Target(Closure , CallSite , Object )\r\n --- End of inner exception stack trace ---\r\n at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)\r\n at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)\r\n at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)\r\n at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)\r\n at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)\r\n at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()\r\n at System.Management.Automation.CommandProcessorBase.Complete()","line":" SmeSubmit -requestBase64 (cvt '\"eyJ1cmwiOiJodHRwczovL25maGN3ZWIwMS5lbmVpZ2hib3Job29kcy5jb206NTU1MzkvYXBpL3dlYnNlcnZlci93ZWJzaXRlcz9maWVsZHM9bmFtZSxzdGF0dXMscGh5c2ljYWxfcGF0aCxiaW5kaW5ncyxhcHBsaWNhdGlvbl9wb29sIiwiX2JvZHkiOm51bGwsIm1ldGhvZCI6MCwiaGVhZGVycyI6eyJBY2NlcHQiOlsiYXBwbGljYXRpb24vaGFsK2pzb24iXSwiQWNjZXNzLVRva2VuIjpbIkJlYXJlciBpckFGYzFDWUtLZVJsY2k3RkpPOGIwMjktYUNNZkVYMExPU0hVWHZ1NWwwellEcmJTNDl1ZmciXX0sImNvbnRlbnRUeXBlIjowLCJ3aXRoQ3JlZGVudGlhbHMiOm51bGwsInJlc3BvbnNlVHlwZSI6bnVsbCwiX2JvZHlVaW50OEFycmF5IjpudWxsfQ==\"') -sessionId (cvt '\"q0c4yyddu6d\"') -verbose","offsetInline":2,"scriptLineNumber":126,"scriptStackTrace":"at SmeSubmit, <No file>: line 91\r\nat <ScriptBlock>, <No file>: line 126"}}]}}

**Comment by shhsu** [comment]
@afoster757 
Can you locate logs in %UserProfile%\wac-iis-logs?
Can you repro the issue and send me the resulting log files (specifically imporant ones are `Invoke-LocalHttp-*.log` and `Get-Token-*.log`)
