### ISSUE TITLE
Can't connect to server with only TLS 1.2

### ISSUE THREAD

**Issue by centreboard** [Microsoft/IIS.WebManager#499]
Running Windows Admin Centre 1910 with msft.iis.iis-management 0.1.3042563 locally on a Windows 10 PC.

I was able to setup and use the IIS extension with our web servers previously. Operations have now configured the web servers to now use only TLS 1.2 and the extension shows

>Unknown error has occurred when trying to initialize Web Server Module: "The underlying connection was closed: An unexpected error occurred on a receive."

Which looks like it's trying to use the the wrong TLS version to make connections.

I note the Windows Admin Centre `SmeDesktop.exe.config` is using .Net Framework 4.5.2 with .Net 4 compatibility
```
<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
```
which (if it's the correct process) would explain why it's not using TLS 1.2.

Hope this is the right place to raise this and please let me know what further information would be useful.

**Comment by shhsu** [comment]
This is an issue for Windows Admin Center https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/faq
I am not aware of any public channel for opening a issue. I am pinging them internally.

**Comment by shhsu** [comment]
@centreboard 
``` Operations have now configured the web servers to now use only TLS 1.2 and the extension shows```
Can you share what exact settings are changed for repro purpose?
