### ISSUE TITLE
IIS Manager not visible on WAC connection with limited access

### ISSUE THREAD

**Issue by dtsob75** [Microsoft/IIS.WebManager#502]
We are trying to use iis mgr ext in WAC to allow developers to manager websites only (no other access should be available).  IIS Mgr ext seems to be the best option for this.  However, when we create role based access control in wac and then use "managing as" with one of the accounts assigned to the "Windows Admin Center Administrators" group, the installed IIS Extension does not show up. If we log back in with a user that has full admin, the extension is visible.

**Comment by bariscaglar** [comment]
This is not a scenario we tested in. Our assumption was WAC is usable only by administrators. I'll assign this to @shhsu for further investigation.

**Comment by ephos** [comment]
This is the primary use case for us as well.  We need to be able to give view access to other folks to view IIS settings without giving them admin to IIS or then server itself.

**Comment by AaronSadlerUK** [comment]
Nearly a year on and there is no progress on this?

**Comment by yaqiyang** [comment]
We only support use it as admin for now
