### ISSUE TITLE
Run IIS.WebManager app error

### ISSUE THREAD

**Issue by daouxv** [Microsoft/IIS.WebManager#503]
Run script: build.ps1.

It can build success, but the page does’t work.

![image](https://user-images.githubusercontent.com/48527326/73912866-9a854e80-48f0-11ea-8a14-37566c5f2219.png)

```
main.ts:20 Error: StaticInjectorError(AppModule)[Runtime -> FilesService]: 
  StaticInjectorError(Platform: core)[Runtime -> FilesService]: 
    NullInjectorError: No provider for FilesService!
    at NullInjector.get (core.js:3903)
    at resolveToken (core.js:4221)
    at tryResolveToken (core.js:4152)
    at StaticInjector.get (core.js:4014)
    at resolveToken (core.js:4221)
    at tryResolveToken (core.js:4152)
    at StaticInjector.get (core.js:4014)
    at resolveNgModuleDep (core.js:24475)
    at _createClass (core.js:24545)
    at _createProviderInstance (core.js:24508)
```

env: 
node 8.17.0
window server 2016

**Comment by ColinRaaijmakers** [comment]
![error](https://user-images.githubusercontent.com/1965665/74645437-39733b80-5178-11ea-9770-8b2bbb350d92.JPG)
Same here. Reproduce: Download source, build, upload to iis and run.

**Comment by lannotimo** [comment]
Dirty fix, change the Injectable attribute in src/app/files/files.service.ts to: `@Injectable({providedIn: 'root'})`.

**Comment by yaqiyang** [comment]
We don't seem to have this issue anymore

**Comment by kimboslice99** [comment]
This is definitely still an issue.

**Comment by dsg-sstoyanov** [comment]
@kimboslice99 You can check the fork that I have prepared at https://github.com/SellerCloudTeam/IIS.WebManager

Soon this repository won't be public so you might want to fork it on your end, or download the ready-to-use Releases.
