### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Access Keys_WAT: Default "Lang" attribute is not provided for the page.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#58]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #ScreenReader; #WCAG3.1.1; #C+E-H; #Edge

**Environment Details:** 
**URL:** https://localhost:55539/security/tokens
**Browser Details:** Edge(42.17134.1.0)
Web Accessibility Toolbar

**Repro Steps:**
1.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
2.Download and install "Microsoft IIS Administration" application.
3.Tab till "Skip This" button and Press Enter.
4.Tab till "Get Access Token" link and Press Enter.
5.Enable WAT.
6.Go to Doc Info-->Show Lang Attributes.
7.Verify default language is provided for page.

**Actual Result:**
Default "Lang" attribute is not provided for any page of the application.

**NOTE:** **Same issue is observed in "Access Key Purpose" and "Access Token" page.**

**Expected Result:**
Each and every page of the application should contain default "Lang" attribute.

**User Impact:**
Screen Reader users find difficulty in using the application if no default language is provided.

**Attachment:**
![bug_58_access keys_no lang attribute](https://user-images.githubusercontent.com/38523250/44566294-606ece00-a78a-11e8-8a96-87a25034539d.png)

**Comment by jhkimnew** [comment]
Fixed

**Comment by fsteffi** [comment]
#A11ySev2;

**Comment by fsteffi** [comment]
#closed;
manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](http://www.iis.net/) home page will  be removed.
