### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Access Keys_Keyboard: Focus order is not proper when "Delete" and "Refresh" pop ups are opened. Narrator is not reading in a meaningful sequence.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#61]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #Keyboard; #WCAG2.4.3; #C+E-H; #Edge

**Environment Details:**
**URL:** https://localhost:55539/security/tokens
**Browser Details:** Edge(42.17134.1.0)
Keyboard

**Repro Steps:**
1.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
2.Download and install "Microsoft IIS Administration" application.
3.Tab till "Skip This" button and Press Enter.
4.Tab till "Get Access Token" link and Press Enter.
5.Tab till "Refresh" button and press enter.
6.Verify focus order in "Refresh" pop up.

**Actual Result:**
Focus order is not proper when "Delete" and "Refresh" pop ups are opened.

**NOTE**: Issue is observed for both pop ups.

**Expected Result:**
Focus first should go to whole pop up first at that time screen reader should read the message inside the pop up. After that focus should go to "OK" button. Focus should not go to non interactive content alone.

**User Impact:**
Screen Reader users find difficulty in using the application if screen reader is not reading content in meaningful sequence. They can not get complete information.

**Attachment:**
[Bug_61_Access Keys_Focus Order.pptx](https://github.com/Microsoft/IIS.WebManager/files/2317234/Bug_61_Access.Keys_Focus.Order.pptx)

**Comment by jhkimnew** [comment]
This seems to be fixed already. Now, only OK and Cancel buttons have the input focus.

**Comment by jhkimnew** [comment]
Reactivating because this is still reproducible with Edge. But not reproducible in Chrome.

**Comment by jhkimnew** [comment]
This issue is duplicated to https://github.com/Microsoft/IIS.Administration/issues/210.

**Comment by fsteffi** [comment]
#A11ySev4;
