### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Access Key Purpose_Screen Reader: Narrator is reading background page controls instead of reading the first control of pop up when we open the "Access Key Purpose" pop up. Issue is observed through out the application

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#66]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #ScreenReader; #WCAG1.3.2; #Narrator; #NVDA; #C+E-H; #Chrome; #Edge

**Environment Details:**
**URL:** https://localhost:55539/security/tokens
**Browser Details:** Edge(42.17134.1.0), Chrome(68.0.3440.106)
**Screen Reader:** Narrator, NVDA

**Repro Steps:**
1.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
2.Download and install "Microsoft IIS Administration" application.
3.Tab till "Skip This" button and Press Enter.
4.Tab till "Get Access Token" link and Press Enter.
5.Tab till "Create Access Key" button and press enter.
6.Start Narrator.
7.Verify how narrator is reading contents in pop up.

**Actual Result:**
Narrator is reading background page controls instead of reading the first control of pop up when we open the "Access Key Purpose" pop up.

**NOTE:** Same issue is observed with keyboard as well.
                  Same issue is observed in "Chrome" browser as well. 
                 **Issue is observed through out the application for all pop ups.**

**Expected Result:**
Narrator focus should go to the first control of pop up when we open the pop up instead of going to the background controls.

**User Impact:**
Screen Reader users can not understand the application if narrator is not reading controls on page in a meaningful sequence.

**Attachment:**
[Bug_66_Access Key Purpose_Meaningful Sequence issue.pptx](https://github.com/Microsoft/IIS.WebManager/files/2317411/Bug_66_Access.Key.Purpose_Meaningful.Sequence.issue.pptx)

**Comment by jhkimnew** [comment]
Fixed

**Comment by fsteffi** [comment]
#A11ySev2;

**Comment by fsteffi** [comment]
#closed;
manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](http://www.iis.net/) home page will  be removed.
