### ISSUE TITLE
Home Page: "Download Microsoft IIS Administration" link appears as button and it is not accessible using space bar key.

### ISSUE THREAD

**Issue by accessibility18** [Microsoft/IIS.WebManager#72]
**Environment Details:**
URL: https://manage.iis.net/
Browser: Microsoft Edge 42.17134.1.0, Google Chrome Version 68.0.3440.106
Issue: Usability 

**Repro Steps:**
1. Open "Microsoft IIS" Home Page using the URL: https://manage.iis.net/
2. Validate that no usability or design issue present in the page.

**Actual Result:**
"Download Microsoft IIS Administration" link appears as button. Since, links are expected to be triggered using the Enter key. But we are unable to open these links by pressing Enter Key.

**Expected Result**:
Link is different in appearance than button and their functionality as well differ. To clearly indicate links, underline them when possible. There should be some visual state change other than color when hovering or focusing on links. 
Link should be accessible through keyboard using Space Bar key

**User Impact:**
Here since "Download Microsoft IIS Administration" link appear as button, so user will think that after selecting it, software will be downloaded. But this actually does not happen because it is a link and it will navigate them to an external site to download the software. 
Since links can be selected using only "Space Bar" key, so keyboard users and screen reader users will try to access it using space bar, but they will be unable to select it, because by design it is a button.

**Note:**
Similar issue is observed with "Microsoft IIS" and "Not Connected" link where user is unable to access these links using space bar key.

**Attachment:**
[Bug 72_ Link appears and behave as button.pptx](https://github.com/Microsoft/IIS.WebManager/files/2317746/Bug.72_.Link.appears.and.behave.as.button.pptx)

**Comment by jhkimnew** [comment]
I think this is a design issue rather than an accessibility issue.

To make <a href> link to support spacebar is not simple.
When we consider changing the UI design, we should fix this together.
We should not use a link which looks like a button.
