### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Access Keys_Screen Reader[Scan Mode]: Narrator is reading just "Headingh level 2" but not reading the "Expires in" heading when we press short cut key "H" in scan mode.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#77]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #ScreenReader; #WCAG1.3.2; #Narrator; #NVDA; #C+E-H; #Chrome; #Edge

**Environment Details:**
**URL:** https://localhost:55539/security/tokens
**Browser Details:** Edge(42.17134.1.0),Chrome(68.0.3440.106)
**Screen Reader**: Narrator, NVDA

**Repro Steps:**
1.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
2.Download and install "Microsoft IIS Administration" application.
3.Tab till "Skip This" button and Press Enter.
4.Tab till "Get Access Token" link and Press Enter.
5.Tab till "Create Access Token" button and press enter.
6.Enable Scan mode(Caps Lock + Spacebar)
6.Start Narrator and press "H" key to navigate all headings on page
7.Verify narrator is reading all controls present inside "Access Key Purpose" pop up.

**Actual Result:**
 Narrator is reading just "Heading level 2" but not reading the "Expires in" heading when we press short cut key "H" in scan mode.

**NOTE**: Same issue is observed in "Chrome".

**Expected Result:**
Narrator should read heading name properly with heading level when we press short cut "H" in scan mode.

**User Impact:**
Screen Reader users can not use short cuts in scan mode if few shortcuts are not working in scan mode.

**Attachment:**
[Bug_77_Access Keys_Heading level issue.pptx](https://github.com/Microsoft/IIS.WebManager/files/2318022/Bug_77_Access.Keys_Heading.level.issue.pptx)

**Comment by jhkimnew** [comment]
I can't reproduce this issue. This issue seems to be already fixed. Please reactivate if this issue still happens.

**Comment by fsteffi** [comment]
#A11ySev2;

**Comment by fsteffi** [comment]
#closed;
manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](http://www.iis.net/) home page will  be removed.
