### ISSUE TITLE
[Accessibility] A11y_Manage.IIS.Net_Access Keys_Screen Reader: NVDA is not reading "Ok" button(even when focus is on "OK") when we open "Refresh" or "Delete" pop ups.NVDA is just reading the content on pop up.

### ISSUE THREAD

**Issue by Accessibility56** [Microsoft/IIS.WebManager#83]
GitHubTags: #A11yTCS; #A11yMAS; #DesktopWeb; #Win10; #A11y_Manage.IIS.Net; #.NETWebsites; #ScreenReader; #WCAG1.3.2; #NVDA; #C+E-H; #Chrome

**Environment Details:**
**URL:** https://localhost:55539/security/tokens
**Browser Details:** Chrome(68.0.3440.106)
**Screen Reader:** NVDA

**Repro Steps:**
1.Open "Microsoft IIS" application using the URL: https://manage.iis.net/
2.Download and install "Microsoft IIS Administration" application.
3.Tab till "Skip This" button and Press Enter.
4.Tab till "Get Access Token" link and Press Enter.
5.Start NVDA.
6.Tab till "Refresh/Delete button and press enter.

**Actual Result:**
 NVDA is not reading "Ok" button when we open "Refresh" or "Delete" pop ups. NVDA is just reading the content on pop up.

**Expected Result:**
NVDA should read "Ok" button along with the content on page when focus is on "Ok" button.

**User Impact:**
Screen Reader users can not know that "Ok" control is present on pop up if NVDA is not reading it. User may not complete full operation if screen reader is not reading all controls on page.

**Attachment:**
[Bug_83_Access Key_NVDA is not reading OK button.pptx](https://github.com/Microsoft/IIS.WebManager/files/2318199/Bug_83_Access.Key_NVDA.is.not.reading.OK.button.pptx)

**Comment by jhkimnew** [comment]
Fixed

**Comment by fsteffi** [comment]
#A11ySev2;

**Comment by Yashi1201** [comment]
#Closed;
Manage.iis.net is deprecated. The "Manage IIS" button on the [www.iis.net](http://www.iis.net/) home page will be removed.
